#!/usr/bin/env python

from getnear.config import validate
from getnear.config import Tagged as T, Untagged as U, Ignore as _
from getnear.eseries import ESeries
from getnear.sync import sync
import sys

hostname, password = sys.argv[1:]

config = validate((
        (        1,  2,  3,  4,  5,  6,  7,  8),
        (        1,  1,  1,  1, 12, 12, 14,  1),
        {
             1: (U,  U,  U,  U,  _,  _,  _,  T),
            12: (_,  _,  _,  _,  U,  U,  _,  T),
            14: (_,  _,  _,  _,  _,  _,  U,  T),
        }
        ))

switch = ESeries(hostname, password)

# 8: trunk
# 7: apple-tv
# 6: console
# 5: console

switch.sync(config)
