#!/usr/bin/env python

from getnear.config import parse
from getnear.config import Tagged as T, Untagged as U, Ignore as _
from getnear.eseries import ESeries
from getnear.sync import sync
import sys

hostname, password = sys.argv[1:]

config = (
        ( 1,  2,  3,  4),
        ( 1,  1, 12, 34),
        {
             1: (T, T, _, _),
            12: (T, _, U, _),
            15: (T, T, _, _),
            35: (T, _, _, U),
        }
        )

switch = ESeries(hostname, password)

switch.enable_vlans()
switch.add_vlan(14)
switch.add_vlan(12)

#                                  # 1  2  3  4  5  6  7  8
switch.set_port_vlan_membership( 1, (U, U, U, U, _, _, _, T))
switch.set_port_vlan_membership(12, (_, _, _, _, U, U, _, T))
switch.set_port_vlan_membership(14, (_, _, _, _, _, _, U, T))
switch.set_port_pvid(1,  1)
switch.set_port_pvid(2,  1)
switch.set_port_pvid(3,  1)
switch.set_port_pvid(4,  1)
switch.set_port_pvid(5, 12)
switch.set_port_pvid(6, 12)
switch.set_port_pvid(7, 14)
switch.set_port_pvid(8,  1)

#sync(config, switch)

# 8: trunk
# 7: apple-tv
# 6: console
# 5: console
