#!/usr/bin/env python

from getnear.config import parse
from getnear.tseries import TSeries
from getnear.sync import sync
import sys

hostname, password = sys.argv[1:]

config = parse('''
        ports   05 06 07 08
        pvids   01 01 12 35
        vlan 01  T  T  _  _
        vlan 12  T  _  U  _
        vlan 15  T  T  _  _
        vlan 35  T  _  _  U
        '''.split())

switch = TSeries(hostname, password)

sync(config, switch)
