#!/usr/bin/env python

from getnear.tseries import TSeries
import sys

def info(message):
    print(f'getnear: {message}')

default_password = 'password'
hostname, password = sys.argv[1:3]

t = TSeries()

info('logging in')
try:
    t.connect(hostname)
    t.admin_mode()
    t.login(password)
except:
    info('using default password')
    t.connect(hostname)
    t.admin_mode()
    t.login(default_password)
    info('changing password')
    t.change_password(default_password, password)
    t.connect(hostname)
    t.admin_mode()
    t.login(password)

def set_config():
    t.set_port_vlan_participation(1, 1, True)

    t.add_vlan(12)
    t.set_port_vlan_tagging(1, 12, True)
    t.set_port_vlan_participation(1, 12, True)

    t.add_vlan(15)
    t.set_port_vlan_participation(1, 15, True)
    t.set_port_vlan_tagging(1, 15, True)

    t.add_vlan(35)
    t.set_port_vlan_participation(1, 35, True)
    t.set_port_vlan_tagging(1, 35, True)
    
    t.set_port_vlan_participation(4, 1, False)
    t.set_port_vlan_participation(4, 35, True)
    t.set_port_vlan_participation(4, 15, False)
    t.set_port_pvid(4, 35)

    t.set_port_vlan_participation(3, 1, False)
    t.set_port_vlan_participation(3, 12, True)
    t.set_port_pvid(3, 12)
    t.set_port_vlan_tagging(3, 12, False)

    t.set_port_vlan_participation(5, 1, True)
    t.set_port_vlan_participation(5, 15, True)
    t.set_port_pvid(5, 1)
    t.set_port_vlan_tagging(5, 1, True)
    t.set_port_vlan_tagging(5, 15, True)
    
    t.set_port_vlan_participation(2, 1, True)
    t.set_port_vlan_participation(2, 15, True)
    t.set_port_vlan_participation(2, 35, False)
    t.set_port_pvid(2, 1)
    t.set_port_vlan_tagging(2, 1, True)
    t.set_port_vlan_tagging(2, 15, True)

def get_config():
    info('fetching config')
    for vlan_id in t.get_vlan_ids():
        for port, (included, tagged) in t.get_vlan(vlan_id):
            if included:
                print('vlan_id', vlan_id, 'port', port, 'tagged', tagged)

    for port, pvids in t.get_port_pvids():
        print('port', port, 'pvids', pvids)

get_config()
set_config()
t.debug(False)
#get_config()

t.exit()
